/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
HALLO
#include <stdio.h>
#include <string.h>

typedef enum{ NONE = -1, GFORTH = 0, SWIFTFORTH, VFX } SwigTargetSystem;
SwigTargetSystem swigTargetSystem = NONE;

unsigned char swigPrintStackComments = 1;

/* constants */
void swigIntConstant( long constant, char *name )
{
	printf( "%ld\tconstant %s\n", constant, name );
}

void swigFloatConstant( double constant, char *name )
{
	char buffer[128];
	sprintf( buffer, "%f", constant );

	/* if the constant contains no exponent, add one */
	unsigned char containsExponent = 0;
	char *s;
	for( s = buffer; *s != 0; s++ )
		if( *s == 'e' || *s == 'E' )
			break;

	/* exponent found */
	if( *s != 0 )
		printf( "%s\tfconstant %s\n", buffer, name );
	/* not found */
	else
		printf( "%se0\tfconstant %s\n", buffer, name );
}

void swigStringConstant( char* constant, char *name )
{
	char c;
	printf( ": %s s\\\" ", name );
	while(c=*constant++) {
		switch(c) {
			case '\b': printf( "\\b" ); break;
			case '\e': printf( "\\e" ); break;
			case '\n': printf( "\\n" ); break;
			case '\f': printf( "\\f" ); break;
			case '\r': printf( "\\r" ); break;
			case '\t': printf( "\\t" ); break;
			case '"' : printf( "\\q" ); break;
			default: if(c < 0x20)
				 	printf("\\x%02x", c);
				 else
					printf("%c", c); break;
		}
	}
	printf(	"\" ;\n" );
}

/* functions */
void swigFunction( char* gforth, char *swiftForth, char *vfx, char *stackComment )
{
	if( swigTargetSystem == GFORTH )
		printf( gforth );
	else if( swigTargetSystem == SWIFTFORTH )
		printf( swiftForth );
	else if( swigTargetSystem == VFX )
		printf( vfx );

	if( swigPrintStackComments )
		printf( stackComment );

	printf( "\n" );
}

void swigUsage( char **argv )
{
	fprintf( stderr, "Usage: %s [-gforth|-swiftforth|-vfx]\n", argv[0] );
}

int main( int argc, char **argv )
{
	int i;

	/* check arguments */
	for( i = 1; i < argc; i++ )
		if( strcmp( argv[i], "-gforth" ) == 0 )
			swigTargetSystem = GFORTH;
		else if( strcmp( argv[i], "-swiftforth" ) == 0 )
			swigTargetSystem = SWIFTFORTH;
		else if( strcmp( argv[i], "-vfx" ) == 0 )
			swigTargetSystem = VFX;

	if( swigTargetSystem == NONE )
	{
		fprintf( stderr, "Error: no target system specified\n" );
		swigUsage( argv );
		return 1;
	}

	/* primer */
	printf( "\\ This file has been generated using SWIG and fsi,\n"
		"\\ and is already platform dependent, search for the corresponding\n"
		"\\ fsi-file to compile it where no one has compiled it before ;)\n"
		"\\ GForth has its own dynamic loader and doesn't need addional C-Code.\n"
		"\\ That's why this file contains normal Gforth-code( version 0.6.9 or higher )\n"
		"\\ and could be used directly with include or require.\n"
		"\\ As all comments are stripped during the compilation, please\n"
		"\\ insert the copyright notice of the original file here.\n"
	);


	swigFunction( "c-function select select n a a a a -- n", "FUNCTION: select", "EXTERN: n C select( n a a a a );", "" );
	swigFunction( "c-function pselect pselect n a a a a a -- n", "FUNCTION: pselect", "EXTERN: n C pselect( n a a a a a );", "" );
	swigFunction( "c-function my_net_init my_net_init a a -- n", "FUNCTION: my_net_init", "EXTERN: n C my_net_init( a a );", "" );
	swigFunction( "c-function my_net_local_init my_net_local_init a -- void", "FUNCTION: my_net_local_init", "EXTERN: void C my_net_local_init( a );", "" );
	swigFunction( "c-function net_end net_end a -- void", "FUNCTION: net_end", "EXTERN: void C net_end( a );", "" );
	swigFunction( "c-function net_clear net_clear a -- void", "FUNCTION: net_clear", "EXTERN: void C net_clear( a );", "" );
	swigFunction( "c-function net_realloc net_realloc a n -- n", "FUNCTION: net_realloc", "EXTERN: n C net_realloc( a n );", "" );
	swigFunction( "c-function net_flush net_flush a -- n", "FUNCTION: net_flush", "EXTERN: n C net_flush( a );", "" );
	swigFunction( "c-function my_net_write my_net_write a a n -- n", "FUNCTION: my_net_write", "EXTERN: n C my_net_write( a a n );", "" );
	swigFunction( "c-function net_write_command net_write_command a n a n a n -- n", "FUNCTION: net_write_command", "EXTERN: n C net_write_command( a n a n a n );", "" );
	swigFunction( "c-function net_real_write net_real_write a a n -- n", "FUNCTION: net_real_write", "EXTERN: n C net_real_write( a a n );", "" );
	swigFunction( "c-function my_net_read my_net_read a -- n", "FUNCTION: my_net_read", "EXTERN: n C my_net_read( a );", "" );
	swigFunction( "c-function my_connect my_connect n a n n -- n", "FUNCTION: my_connect", "EXTERN: n C my_connect( n a n n );", "" );
	swigFunction( "c-function randominit randominit a n n -- void", "FUNCTION: randominit", "EXTERN: void C randominit( a n n );", "" );
	swigFunction( "c-function my_rnd my_rnd a -- r", "FUNCTION: my_rnd", "EXTERN: r C my_rnd( a );", "" );
	swigFunction( "c-function create_random_string create_random_string a n a -- void", "FUNCTION: create_random_string", "EXTERN: void C create_random_string( a n a );", "" );
	swigFunction( "c-function hash_password hash_password a a n -- void", "FUNCTION: hash_password", "EXTERN: void C hash_password( a a n );", "" );
	swigFunction( "c-function make_scrambled_password_323 make_scrambled_password_323 a a -- void", "FUNCTION: make_scrambled_password_323", "EXTERN: void C make_scrambled_password_323( a a );", "" );
	swigFunction( "c-function scramble_323 scramble_323 a a a -- void", "FUNCTION: scramble_323", "EXTERN: void C scramble_323( a a a );", "" );
	swigFunction( "c-function check_scramble_323 check_scramble_323 a a a -- n", "FUNCTION: check_scramble_323", "EXTERN: n C check_scramble_323( a a a );", "" );
	swigFunction( "c-function get_salt_from_password_323 get_salt_from_password_323 a a -- void", "FUNCTION: get_salt_from_password_323", "EXTERN: void C get_salt_from_password_323( a a );", "" );
	swigFunction( "c-function make_password_from_salt_323 make_password_from_salt_323 a a -- void", "FUNCTION: make_password_from_salt_323", "EXTERN: void C make_password_from_salt_323( a a );", "" );
	swigFunction( "c-function make_scrambled_password make_scrambled_password a a -- void", "FUNCTION: make_scrambled_password", "EXTERN: void C make_scrambled_password( a a );", "" );
	swigFunction( "c-function scramble scramble a a a -- void", "FUNCTION: scramble", "EXTERN: void C scramble( a a a );", "" );
	swigFunction( "c-function check_scramble check_scramble a a a -- n", "FUNCTION: check_scramble", "EXTERN: n C check_scramble( a a a );", "" );
	swigFunction( "c-function get_salt_from_password get_salt_from_password a a -- void", "FUNCTION: get_salt_from_password", "EXTERN: void C get_salt_from_password( a a );", "" );
	swigFunction( "c-function make_password_from_salt make_password_from_salt a a -- void", "FUNCTION: make_password_from_salt", "EXTERN: void C make_password_from_salt( a a );", "" );
	swigFunction( "c-function octet2hex octet2hex a a n -- a", "FUNCTION: octet2hex", "EXTERN: a C octet2hex( a a n );", "" );
	swigFunction( "c-function get_tty_password get_tty_password a -- a", "FUNCTION: get_tty_password", "EXTERN: a C get_tty_password( a );", "" );
	swigFunction( "c-function mysql_errno_to_sqlstate mysql_errno_to_sqlstate n -- a", "FUNCTION: mysql_errno_to_sqlstate", "EXTERN: a C mysql_errno_to_sqlstate( n );", "" );
	swigFunction( "c-function my_init my_init  -- n", "FUNCTION: my_init", "EXTERN: n C my_init(  );", "" );
	swigFunction( "c-function modify_defaults_file modify_defaults_file a a a a n -- n", "FUNCTION: modify_defaults_file", "EXTERN: n C modify_defaults_file( a a a a n );", "" );
	swigFunction( "c-function load_defaults load_defaults a a a a -- n", "FUNCTION: load_defaults", "EXTERN: n C load_defaults( a a a a );", "" );
	swigFunction( "c-function my_thread_init my_thread_init  -- n", "FUNCTION: my_thread_init", "EXTERN: n C my_thread_init(  );", "" );
	swigFunction( "c-function my_thread_end my_thread_end  -- void", "FUNCTION: my_thread_end", "EXTERN: void C my_thread_end(  );", "" );
	swigFunction( "c-function find_type find_type a a n -- n", "FUNCTION: find_type", "EXTERN: n C find_type( a a n );", "" );
	swigFunction( "c-function make_type make_type a n a -- void", "FUNCTION: make_type", "EXTERN: void C make_type( a n a );", "" );
	swigFunction( "c-function get_type get_type a n -- a", "FUNCTION: get_type", "EXTERN: a C get_type( a n );", "" );
	swigFunction( "c-function copy_typelib copy_typelib a a -- a", "FUNCTION: copy_typelib", "EXTERN: a C copy_typelib( a a );", "" );
	swigFunction( "c-function list_add list_add a a -- a", "FUNCTION: list_add", "EXTERN: a C list_add( a a );", "" );
	swigFunction( "c-function list_delete list_delete a a -- a", "FUNCTION: list_delete", "EXTERN: a C list_delete( a a );", "" );
	swigFunction( "c-function list_cons list_cons a a -- a", "FUNCTION: list_cons", "EXTERN: a C list_cons( a a );", "" );
	swigFunction( "c-function list_reverse list_reverse a -- a", "FUNCTION: list_reverse", "EXTERN: a C list_reverse( a );", "" );
	swigFunction( "c-function list_free list_free a n -- void", "FUNCTION: list_free", "EXTERN: void C list_free( a n );", "" );
	swigFunction( "c-function list_length list_length a -- n", "FUNCTION: list_length", "EXTERN: n C list_length( a );", "" );
	swigFunction( "c-function list_walk list_walk a a a -- n", "FUNCTION: list_walk", "EXTERN: n C list_walk( a a a );", "" );
	swigFunction( "c-function mysql_server_init mysql_server_init n a a -- n", "FUNCTION: mysql_server_init", "EXTERN: n C mysql_server_init( n a a );", "" );
	swigFunction( "c-function mysql_server_end mysql_server_end  -- void", "FUNCTION: mysql_server_end", "EXTERN: void C mysql_server_end(  );", "" );
	swigFunction( "c-function mysql_get_parameters mysql_get_parameters  -- a", "FUNCTION: mysql_get_parameters", "EXTERN: a C mysql_get_parameters(  );", "" );
	swigFunction( "c-function mysql_thread_init mysql_thread_init  -- n", "FUNCTION: mysql_thread_init", "EXTERN: n C mysql_thread_init(  );", "" );
	swigFunction( "c-function mysql_thread_end mysql_thread_end  -- void", "FUNCTION: mysql_thread_end", "EXTERN: void C mysql_thread_end(  );", "" );
	swigFunction( "c-function mysql_num_rows mysql_num_rows a -- d", "FUNCTION: mysql_num_rows", "EXTERN: d C mysql_num_rows( a );", "" );
	swigFunction( "c-function mysql_num_fields mysql_num_fields a -- n", "FUNCTION: mysql_num_fields", "EXTERN: n C mysql_num_fields( a );", "" );
	swigFunction( "c-function mysql_eof mysql_eof a -- n", "FUNCTION: mysql_eof", "EXTERN: n C mysql_eof( a );", "" );
	swigFunction( "c-function mysql_fetch_field_direct mysql_fetch_field_direct a n -- a", "FUNCTION: mysql_fetch_field_direct", "EXTERN: a C mysql_fetch_field_direct( a n );", "" );
	swigFunction( "c-function mysql_fetch_fields mysql_fetch_fields a -- a", "FUNCTION: mysql_fetch_fields", "EXTERN: a C mysql_fetch_fields( a );", "" );
	swigFunction( "c-function mysql_row_tell mysql_row_tell a -- a", "FUNCTION: mysql_row_tell", "EXTERN: a C mysql_row_tell( a );", "" );
	swigFunction( "c-function mysql_field_tell mysql_field_tell a -- n", "FUNCTION: mysql_field_tell", "EXTERN: n C mysql_field_tell( a );", "" );
	swigFunction( "c-function mysql_field_count mysql_field_count a -- n", "FUNCTION: mysql_field_count", "EXTERN: n C mysql_field_count( a );", "" );
	swigFunction( "c-function mysql_affected_rows mysql_affected_rows a -- d", "FUNCTION: mysql_affected_rows", "EXTERN: d C mysql_affected_rows( a );", "" );
	swigFunction( "c-function mysql_insert_id mysql_insert_id a -- d", "FUNCTION: mysql_insert_id", "EXTERN: d C mysql_insert_id( a );", "" );
	swigFunction( "c-function mysql_errno mysql_errno a -- n", "FUNCTION: mysql_errno", "EXTERN: n C mysql_errno( a );", "" );
	swigFunction( "c-function mysql_error mysql_error a -- a", "FUNCTION: mysql_error", "EXTERN: a C mysql_error( a );", "" );
	swigFunction( "c-function mysql_sqlstate mysql_sqlstate a -- a", "FUNCTION: mysql_sqlstate", "EXTERN: a C mysql_sqlstate( a );", "" );
	swigFunction( "c-function mysql_warning_count mysql_warning_count a -- n", "FUNCTION: mysql_warning_count", "EXTERN: n C mysql_warning_count( a );", "" );
	swigFunction( "c-function mysql_info mysql_info a -- a", "FUNCTION: mysql_info", "EXTERN: a C mysql_info( a );", "" );
	swigFunction( "c-function mysql_thread_id mysql_thread_id a -- n", "FUNCTION: mysql_thread_id", "EXTERN: n C mysql_thread_id( a );", "" );
	swigFunction( "c-function mysql_character_set_name mysql_character_set_name a -- a", "FUNCTION: mysql_character_set_name", "EXTERN: a C mysql_character_set_name( a );", "" );
	swigFunction( "c-function mysql_set_character_set mysql_set_character_set a a -- n", "FUNCTION: mysql_set_character_set", "EXTERN: n C mysql_set_character_set( a a );", "" );
	swigFunction( "c-function mysql_init mysql_init a -- a", "FUNCTION: mysql_init", "EXTERN: a C mysql_init( a );", "" );
	swigFunction( "c-function mysql_ssl_set mysql_ssl_set a a a a a a -- n", "FUNCTION: mysql_ssl_set", "EXTERN: n C mysql_ssl_set( a a a a a a );", "" );
	swigFunction( "c-function mysql_get_ssl_cipher mysql_get_ssl_cipher a -- a", "FUNCTION: mysql_get_ssl_cipher", "EXTERN: a C mysql_get_ssl_cipher( a );", "" );
	swigFunction( "c-function mysql_change_user mysql_change_user a a a a -- n", "FUNCTION: mysql_change_user", "EXTERN: n C mysql_change_user( a a a a );", "" );
	swigFunction( "c-function mysql_real_connect mysql_real_connect a a a a a n a n -- a", "FUNCTION: mysql_real_connect", "EXTERN: a C mysql_real_connect( a a a a a n a n );", "" );
	swigFunction( "c-function mysql_select_db mysql_select_db a a -- n", "FUNCTION: mysql_select_db", "EXTERN: n C mysql_select_db( a a );", "" );
	swigFunction( "c-function mysql_query mysql_query a a -- n", "FUNCTION: mysql_query", "EXTERN: n C mysql_query( a a );", "" );
	swigFunction( "c-function mysql_send_query mysql_send_query a a n -- n", "FUNCTION: mysql_send_query", "EXTERN: n C mysql_send_query( a a n );", "" );
	swigFunction( "c-function mysql_real_query mysql_real_query a a n -- n", "FUNCTION: mysql_real_query", "EXTERN: n C mysql_real_query( a a n );", "" );
	swigFunction( "c-function mysql_store_result mysql_store_result a -- a", "FUNCTION: mysql_store_result", "EXTERN: a C mysql_store_result( a );", "" );
	swigFunction( "c-function mysql_use_result mysql_use_result a -- a", "FUNCTION: mysql_use_result", "EXTERN: a C mysql_use_result( a );", "" );
	swigFunction( "c-function mysql_master_query mysql_master_query a a n -- n", "FUNCTION: mysql_master_query", "EXTERN: n C mysql_master_query( a a n );", "" );
	swigFunction( "c-function mysql_master_send_query mysql_master_send_query a a n -- n", "FUNCTION: mysql_master_send_query", "EXTERN: n C mysql_master_send_query( a a n );", "" );
	swigFunction( "c-function mysql_slave_query mysql_slave_query a a n -- n", "FUNCTION: mysql_slave_query", "EXTERN: n C mysql_slave_query( a a n );", "" );
	swigFunction( "c-function mysql_slave_send_query mysql_slave_send_query a a n -- n", "FUNCTION: mysql_slave_send_query", "EXTERN: n C mysql_slave_send_query( a a n );", "" );
	swigFunction( "c-function mysql_get_character_set_info mysql_get_character_set_info a a -- void", "FUNCTION: mysql_get_character_set_info", "EXTERN: void C mysql_get_character_set_info( a a );", "" );
	swigFunction( "c-function mysql_set_local_infile_handler mysql_set_local_infile_handler a a a a a a -- void", "FUNCTION: mysql_set_local_infile_handler", "EXTERN: void C mysql_set_local_infile_handler( a a a a a a );", "" );
	swigFunction( "c-function mysql_set_local_infile_default mysql_set_local_infile_default a -- void", "FUNCTION: mysql_set_local_infile_default", "EXTERN: void C mysql_set_local_infile_default( a );", "" );
	swigFunction( "c-function mysql_enable_rpl_parse mysql_enable_rpl_parse a -- void", "FUNCTION: mysql_enable_rpl_parse", "EXTERN: void C mysql_enable_rpl_parse( a );", "" );
	swigFunction( "c-function mysql_disable_rpl_parse mysql_disable_rpl_parse a -- void", "FUNCTION: mysql_disable_rpl_parse", "EXTERN: void C mysql_disable_rpl_parse( a );", "" );
	swigFunction( "c-function mysql_rpl_parse_enabled mysql_rpl_parse_enabled a -- n", "FUNCTION: mysql_rpl_parse_enabled", "EXTERN: n C mysql_rpl_parse_enabled( a );", "" );
	swigFunction( "c-function mysql_enable_reads_from_master mysql_enable_reads_from_master a -- void", "FUNCTION: mysql_enable_reads_from_master", "EXTERN: void C mysql_enable_reads_from_master( a );", "" );
	swigFunction( "c-function mysql_disable_reads_from_master mysql_disable_reads_from_master a -- void", "FUNCTION: mysql_disable_reads_from_master", "EXTERN: void C mysql_disable_reads_from_master( a );", "" );
	swigFunction( "c-function mysql_reads_from_master_enabled mysql_reads_from_master_enabled a -- n", "FUNCTION: mysql_reads_from_master_enabled", "EXTERN: n C mysql_reads_from_master_enabled( a );", "" );
	swigFunction( "c-function mysql_rpl_query_type mysql_rpl_query_type a n -- n", "FUNCTION: mysql_rpl_query_type", "EXTERN: n C mysql_rpl_query_type( a n );", "" );
	swigFunction( "c-function mysql_rpl_probe mysql_rpl_probe a -- n", "FUNCTION: mysql_rpl_probe", "EXTERN: n C mysql_rpl_probe( a );", "" );
	swigFunction( "c-function mysql_set_master mysql_set_master a a n a a -- n", "FUNCTION: mysql_set_master", "EXTERN: n C mysql_set_master( a a n a a );", "" );
	swigFunction( "c-function mysql_add_slave mysql_add_slave a a n a a -- n", "FUNCTION: mysql_add_slave", "EXTERN: n C mysql_add_slave( a a n a a );", "" );
	swigFunction( "c-function mysql_shutdown mysql_shutdown a n -- n", "FUNCTION: mysql_shutdown", "EXTERN: n C mysql_shutdown( a n );", "" );
	swigFunction( "c-function mysql_dump_debug_info mysql_dump_debug_info a -- n", "FUNCTION: mysql_dump_debug_info", "EXTERN: n C mysql_dump_debug_info( a );", "" );
	swigFunction( "c-function mysql_refresh mysql_refresh a n -- n", "FUNCTION: mysql_refresh", "EXTERN: n C mysql_refresh( a n );", "" );
	swigFunction( "c-function mysql_kill mysql_kill a n -- n", "FUNCTION: mysql_kill", "EXTERN: n C mysql_kill( a n );", "" );
	swigFunction( "c-function mysql_set_server_option mysql_set_server_option a n -- n", "FUNCTION: mysql_set_server_option", "EXTERN: n C mysql_set_server_option( a n );", "" );
	swigFunction( "c-function mysql_ping mysql_ping a -- n", "FUNCTION: mysql_ping", "EXTERN: n C mysql_ping( a );", "" );
	swigFunction( "c-function mysql_stat mysql_stat a -- a", "FUNCTION: mysql_stat", "EXTERN: a C mysql_stat( a );", "" );
	swigFunction( "c-function mysql_get_server_info mysql_get_server_info a -- a", "FUNCTION: mysql_get_server_info", "EXTERN: a C mysql_get_server_info( a );", "" );
	swigFunction( "c-function mysql_get_client_info mysql_get_client_info  -- a", "FUNCTION: mysql_get_client_info", "EXTERN: a C mysql_get_client_info(  );", "" );
	swigFunction( "c-function mysql_get_client_version mysql_get_client_version  -- n", "FUNCTION: mysql_get_client_version", "EXTERN: n C mysql_get_client_version(  );", "" );
	swigFunction( "c-function mysql_get_host_info mysql_get_host_info a -- a", "FUNCTION: mysql_get_host_info", "EXTERN: a C mysql_get_host_info( a );", "" );
	swigFunction( "c-function mysql_get_server_version mysql_get_server_version a -- n", "FUNCTION: mysql_get_server_version", "EXTERN: n C mysql_get_server_version( a );", "" );
	swigFunction( "c-function mysql_get_proto_info mysql_get_proto_info a -- n", "FUNCTION: mysql_get_proto_info", "EXTERN: n C mysql_get_proto_info( a );", "" );
	swigFunction( "c-function mysql_list_dbs mysql_list_dbs a a -- a", "FUNCTION: mysql_list_dbs", "EXTERN: a C mysql_list_dbs( a a );", "" );
	swigFunction( "c-function mysql_list_tables mysql_list_tables a a -- a", "FUNCTION: mysql_list_tables", "EXTERN: a C mysql_list_tables( a a );", "" );
	swigFunction( "c-function mysql_list_processes mysql_list_processes a -- a", "FUNCTION: mysql_list_processes", "EXTERN: a C mysql_list_processes( a );", "" );
	swigFunction( "c-function mysql_options mysql_options a n a -- n", "FUNCTION: mysql_options", "EXTERN: n C mysql_options( a n a );", "" );
	swigFunction( "c-function mysql_free_result mysql_free_result a -- void", "FUNCTION: mysql_free_result", "EXTERN: void C mysql_free_result( a );", "" );
	swigFunction( "c-function mysql_data_seek mysql_data_seek a d -- void", "FUNCTION: mysql_data_seek", "EXTERN: void C mysql_data_seek( a d );", "" );
	swigFunction( "c-function mysql_row_seek mysql_row_seek a a -- a", "FUNCTION: mysql_row_seek", "EXTERN: a C mysql_row_seek( a a );", "" );
	swigFunction( "c-function mysql_field_seek mysql_field_seek a n -- n", "FUNCTION: mysql_field_seek", "EXTERN: n C mysql_field_seek( a n );", "" );
	swigFunction( "c-function mysql_fetch_row mysql_fetch_row a -- a", "FUNCTION: mysql_fetch_row", "EXTERN: a C mysql_fetch_row( a );", "" );
	swigFunction( "c-function mysql_fetch_lengths mysql_fetch_lengths a -- a", "FUNCTION: mysql_fetch_lengths", "EXTERN: a C mysql_fetch_lengths( a );", "" );
	swigFunction( "c-function mysql_fetch_field mysql_fetch_field a -- a", "FUNCTION: mysql_fetch_field", "EXTERN: a C mysql_fetch_field( a );", "" );
	swigFunction( "c-function mysql_list_fields mysql_list_fields a a a -- a", "FUNCTION: mysql_list_fields", "EXTERN: a C mysql_list_fields( a a a );", "" );
	swigFunction( "c-function mysql_escape_string mysql_escape_string a a n -- n", "FUNCTION: mysql_escape_string", "EXTERN: n C mysql_escape_string( a a n );", "" );
	swigFunction( "c-function mysql_hex_string mysql_hex_string a a n -- n", "FUNCTION: mysql_hex_string", "EXTERN: n C mysql_hex_string( a a n );", "" );
	swigFunction( "c-function mysql_real_escape_string mysql_real_escape_string a a a n -- n", "FUNCTION: mysql_real_escape_string", "EXTERN: n C mysql_real_escape_string( a a a n );", "" );
	swigFunction( "c-function mysql_debug mysql_debug a -- void", "FUNCTION: mysql_debug", "EXTERN: void C mysql_debug( a );", "" );
	swigFunction( "c-function mysql_odbc_escape_string mysql_odbc_escape_string a a n a n a a -- a", "FUNCTION: mysql_odbc_escape_string", "EXTERN: a C mysql_odbc_escape_string( a a n a n a a );", "" );
	swigFunction( "c-function myodbc_remove_escape myodbc_remove_escape a a -- void", "FUNCTION: myodbc_remove_escape", "EXTERN: void C myodbc_remove_escape( a a );", "" );
	swigFunction( "c-function mysql_thread_safe mysql_thread_safe  -- n", "FUNCTION: mysql_thread_safe", "EXTERN: n C mysql_thread_safe(  );", "" );
	swigFunction( "c-function mysql_embedded mysql_embedded  -- n", "FUNCTION: mysql_embedded", "EXTERN: n C mysql_embedded(  );", "" );
	swigFunction( "c-function mysql_manager_init mysql_manager_init a -- a", "FUNCTION: mysql_manager_init", "EXTERN: a C mysql_manager_init( a );", "" );
	swigFunction( "c-function mysql_manager_connect mysql_manager_connect a a a a n -- a", "FUNCTION: mysql_manager_connect", "EXTERN: a C mysql_manager_connect( a a a a n );", "" );
	swigFunction( "c-function mysql_manager_close mysql_manager_close a -- void", "FUNCTION: mysql_manager_close", "EXTERN: void C mysql_manager_close( a );", "" );
	swigFunction( "c-function mysql_manager_command mysql_manager_command a a n -- n", "FUNCTION: mysql_manager_command", "EXTERN: n C mysql_manager_command( a a n );", "" );
	swigFunction( "c-function mysql_manager_fetch_line mysql_manager_fetch_line a a n -- n", "FUNCTION: mysql_manager_fetch_line", "EXTERN: n C mysql_manager_fetch_line( a a n );", "" );
	swigFunction( "c-function mysql_read_query_result mysql_read_query_result a -- n", "FUNCTION: mysql_read_query_result", "EXTERN: n C mysql_read_query_result( a );", "" );
	swigFunction( "c-function mysql_stmt_init mysql_stmt_init a -- a", "FUNCTION: mysql_stmt_init", "EXTERN: a C mysql_stmt_init( a );", "" );
	swigFunction( "c-function mysql_stmt_prepare mysql_stmt_prepare a a n -- n", "FUNCTION: mysql_stmt_prepare", "EXTERN: n C mysql_stmt_prepare( a a n );", "" );
	swigFunction( "c-function mysql_stmt_execute mysql_stmt_execute a -- n", "FUNCTION: mysql_stmt_execute", "EXTERN: n C mysql_stmt_execute( a );", "" );
	swigFunction( "c-function mysql_stmt_fetch mysql_stmt_fetch a -- n", "FUNCTION: mysql_stmt_fetch", "EXTERN: n C mysql_stmt_fetch( a );", "" );
	swigFunction( "c-function mysql_stmt_fetch_column mysql_stmt_fetch_column a a n n -- n", "FUNCTION: mysql_stmt_fetch_column", "EXTERN: n C mysql_stmt_fetch_column( a a n n );", "" );
	swigFunction( "c-function mysql_stmt_store_result mysql_stmt_store_result a -- n", "FUNCTION: mysql_stmt_store_result", "EXTERN: n C mysql_stmt_store_result( a );", "" );
	swigFunction( "c-function mysql_stmt_param_count mysql_stmt_param_count a -- n", "FUNCTION: mysql_stmt_param_count", "EXTERN: n C mysql_stmt_param_count( a );", "" );
	swigFunction( "c-function mysql_stmt_attr_set mysql_stmt_attr_set a n a -- n", "FUNCTION: mysql_stmt_attr_set", "EXTERN: n C mysql_stmt_attr_set( a n a );", "" );
	swigFunction( "c-function mysql_stmt_attr_get mysql_stmt_attr_get a n a -- n", "FUNCTION: mysql_stmt_attr_get", "EXTERN: n C mysql_stmt_attr_get( a n a );", "" );
	swigFunction( "c-function mysql_stmt_bind_param mysql_stmt_bind_param a a -- n", "FUNCTION: mysql_stmt_bind_param", "EXTERN: n C mysql_stmt_bind_param( a a );", "" );
	swigFunction( "c-function mysql_stmt_bind_result mysql_stmt_bind_result a a -- n", "FUNCTION: mysql_stmt_bind_result", "EXTERN: n C mysql_stmt_bind_result( a a );", "" );
	swigFunction( "c-function mysql_stmt_close mysql_stmt_close a -- n", "FUNCTION: mysql_stmt_close", "EXTERN: n C mysql_stmt_close( a );", "" );
	swigFunction( "c-function mysql_stmt_reset mysql_stmt_reset a -- n", "FUNCTION: mysql_stmt_reset", "EXTERN: n C mysql_stmt_reset( a );", "" );
	swigFunction( "c-function mysql_stmt_free_result mysql_stmt_free_result a -- n", "FUNCTION: mysql_stmt_free_result", "EXTERN: n C mysql_stmt_free_result( a );", "" );
	swigFunction( "c-function mysql_stmt_send_long_data mysql_stmt_send_long_data a n a n -- n", "FUNCTION: mysql_stmt_send_long_data", "EXTERN: n C mysql_stmt_send_long_data( a n a n );", "" );
	swigFunction( "c-function mysql_stmt_result_metadata mysql_stmt_result_metadata a -- a", "FUNCTION: mysql_stmt_result_metadata", "EXTERN: a C mysql_stmt_result_metadata( a );", "" );
	swigFunction( "c-function mysql_stmt_param_metadata mysql_stmt_param_metadata a -- a", "FUNCTION: mysql_stmt_param_metadata", "EXTERN: a C mysql_stmt_param_metadata( a );", "" );
	swigFunction( "c-function mysql_stmt_errno mysql_stmt_errno a -- n", "FUNCTION: mysql_stmt_errno", "EXTERN: n C mysql_stmt_errno( a );", "" );
	swigFunction( "c-function mysql_stmt_error mysql_stmt_error a -- a", "FUNCTION: mysql_stmt_error", "EXTERN: a C mysql_stmt_error( a );", "" );
	swigFunction( "c-function mysql_stmt_sqlstate mysql_stmt_sqlstate a -- a", "FUNCTION: mysql_stmt_sqlstate", "EXTERN: a C mysql_stmt_sqlstate( a );", "" );
	swigFunction( "c-function mysql_stmt_row_seek mysql_stmt_row_seek a a -- a", "FUNCTION: mysql_stmt_row_seek", "EXTERN: a C mysql_stmt_row_seek( a a );", "" );
	swigFunction( "c-function mysql_stmt_row_tell mysql_stmt_row_tell a -- a", "FUNCTION: mysql_stmt_row_tell", "EXTERN: a C mysql_stmt_row_tell( a );", "" );
	swigFunction( "c-function mysql_stmt_data_seek mysql_stmt_data_seek a d -- void", "FUNCTION: mysql_stmt_data_seek", "EXTERN: void C mysql_stmt_data_seek( a d );", "" );
	swigFunction( "c-function mysql_stmt_num_rows mysql_stmt_num_rows a -- d", "FUNCTION: mysql_stmt_num_rows", "EXTERN: d C mysql_stmt_num_rows( a );", "" );
	swigFunction( "c-function mysql_stmt_affected_rows mysql_stmt_affected_rows a -- d", "FUNCTION: mysql_stmt_affected_rows", "EXTERN: d C mysql_stmt_affected_rows( a );", "" );
	swigFunction( "c-function mysql_stmt_insert_id mysql_stmt_insert_id a -- d", "FUNCTION: mysql_stmt_insert_id", "EXTERN: d C mysql_stmt_insert_id( a );", "" );
	swigFunction( "c-function mysql_stmt_field_count mysql_stmt_field_count a -- n", "FUNCTION: mysql_stmt_field_count", "EXTERN: n C mysql_stmt_field_count( a );", "" );
	swigFunction( "c-function mysql_commit mysql_commit a -- n", "FUNCTION: mysql_commit", "EXTERN: n C mysql_commit( a );", "" );
	swigFunction( "c-function mysql_rollback mysql_rollback a -- n", "FUNCTION: mysql_rollback", "EXTERN: n C mysql_rollback( a );", "" );
	swigFunction( "c-function mysql_autocommit mysql_autocommit a n -- n", "FUNCTION: mysql_autocommit", "EXTERN: n C mysql_autocommit( a n );", "" );
	swigFunction( "c-function mysql_more_results mysql_more_results a -- n", "FUNCTION: mysql_more_results", "EXTERN: n C mysql_more_results( a );", "" );
	swigFunction( "c-function mysql_next_result mysql_next_result a -- n", "FUNCTION: mysql_next_result", "EXTERN: n C mysql_next_result( a );", "" );
	swigFunction( "c-function mysql_close mysql_close a -- void", "FUNCTION: mysql_close", "EXTERN: void C mysql_close( a );", "" );

